In [1]:
import ee 
from GEE_ImageFusion import *
import pandas as pd
import numpy as np
import geopandas as gpd

In [2]:
ee.Authenticate()
ee.Initialize(project='landsat-fusion')

In [3]:
landsat_stat_paths = ["LT05_Metadata_Export.csv", "LE07_Metadata_Export.csv", "LC08_Metadata_Export.csv"]

dtype_mappping = dict(WRS_PATH='int32', WRS_ROW='int32', CLOUD_COVER='int32')


landsat_df = pd.concat([pd.read_csv(p).assign(source=p.split('_')[0]).astype(dtype_mappping) for p in landsat_stat_paths])

landsat_df['date'] = pd.to_datetime(landsat_df['date'])

landsat_df

,system_index,date,WRS_PATH,WRS_ROW,CLOUD_COVER,IMAGE_QUALITY,source
0,LT05_191024_20000317,2000-03-17,191,24,55,9.0,LT05
1,LT05_191024_20000504,2000-05-04,191,24,33,9.0,LT05
2,LT05_191024_20000605,2000-06-05,191,24,31,9.0,LT05
3,LT05_191024_20000621,2000-06-21,191,24,1,9.0,LT05
4,LT05_191024_20000909,2000-09-09,191,24,55,9.0,LT05
...,...,...,...,...,...,...,...
3249,LC08_198025_20170925,2017-09-25,198,25,18,NaN,LC08
3250,LC08_198025_20171027,2017-10-27,198,25,35,NaN,LC08
3251,LC08_198025_20171112,2017-11-12,198,25,81,NaN,LC08
3252,LC08_198025_20171128,2017-11-28,198,25,36,NaN,LC08
3253,LC08_198025_20171214,2017-12-14,198,25,83,NaN,LC08

In [4]:
relevant_tiles = gpd.read_file("relevant_tiles.gpkg").astype({k: dtype_mappping[k] for k in dtype_mappping if k != "CLOUD_COVER"})
relevant_tiles

,WRS_PATH,WRS_ROW,remaining_area,geometry
0,195,27,0.244297,MULTIPOLYGON Z (((1058648.357 6114844.043 7000...
1,194,27,0.425767,MULTIPOLYGON Z (((1230636.971 6114844.043 7000...
2,193,27,0.464225,MULTIPOLYGON Z (((1402625.584 6114844.043 7000...
3,192,27,0.263979,MULTIPOLYGON Z (((1441934.958 6143902.698 7000...
4,196,26,0.328061,"MULTIPOLYGON Z (((954787.273 6352934.763 7000,..."
5,195,26,0.827768,MULTIPOLYGON Z (((1126775.886 6352934.763 7000...
6,194,26,1.000000,MULTIPOLYGON Z (((1298764.499 6352934.763 7000...
7,193,26,0.976172,MULTIPOLYGON Z (((1398333.958 6369279.357 7000...
8,192,26,0.512568,MULTIPOLYGON Z (((1386543.758 6410757.198 7000...
9,197,25,0.413723,"MULTIPOLYGON Z (((854377.092 6597448.438 7000,..."
10,196,25,0.955837,MULTIPOLYGON Z (((1026365.705 6597448.438 7000...
11,195,25,1.000000,MULTIPOLYGON Z (((1198354.318 6597448.438 7000...
12,194,25,1.000000,MULTIPOLYGON Z (((1370342.932 6597448.438 7000...
13,193,25,0.737748,MULTIPOLYGON Z (((1542331.545 6597448.438 7000...
14,192,25,0.256157,MULTIPOLYGON Z (((1589273.136 6626578.799 7000...
15,197,24,0.577176,"MULTIPOLYGON Z (((929740.387 6848911.013 7000,..."
16,196,24,0.996703,"MULTIPOLYGON Z (((1101840.32 6848911.013 7000,..."
17,195,24,1.000000,MULTIPOLYGON Z (((1273828.933 6848911.013 7000...
18,194,24,1.000000,MULTIPOLYGON Z (((1445817.546 6848911.013 7000...
19,193,24,0.999732,"MULTIPOLYGON Z (((1617806.16 6848911.013 7000,..."
20,192,24,0.648927,MULTIPOLYGON Z (((1627745.194 6887844.804 7000...
21,197,23,0.506657,MULTIPOLYGON Z (((1009445.143 7107716.424 7000...
22,196,23,0.907233,MULTIPOLYGON Z (((1004065.633 7151853.886 7000...
23,195,23,0.995895,MULTIPOLYGON Z (((1353533.689 7107716.424 7000...
24,194,23,0.990597,MULTIPOLYGON Z (((1278191.915 7169242.323 7000...
25,193,23,0.830872,MULTIPOLYGON Z (((1538499.249 7147272.161 7000...
26,192,23,0.261510,"MULTIPOLYGON Z (((1472088.946 6893053.46 7000,..."
27,196,22,0.414172,MULTIPOLYGON Z (((1228298.263 7255335.169 7000...
28,195,22,0.382941,MULTIPOLYGON Z (((1396700.217 7243977.012 7000...
29,194,22,0.329961,MULTIPOLYGON Z (((1546065.494 7171981.378 7000...

In [5]:
relevant_landsat_df = landsat_df.merge(relevant_tiles, how='inner', on=['WRS_PATH', 'WRS_ROW'])

In [6]:
def get_borders_for_tile_and_year(data, wrs_path, wrs_row, year, cloud_cover_limit, date_format='%Y-%m-%d'):

    df = data[(data["WRS_PATH"] == wrs_path) & (data["WRS_ROW"] == wrs_row) & (data['CLOUD_COVER'] < cloud_cover_limit)]

    sorted_df = df.sort_values(by='date')

    start_date = pd.to_datetime(sorted_df[sorted_df['date'].dt.year < year]['date'].tail(1).item()) - pd.Timedelta(days=1)


    end_date = pd.to_datetime(sorted_df[sorted_df['date'].dt.year > year]['date'].head(1).item()) + pd.Timedelta(days=1)

    return start_date.strftime(date_format), end_date.strftime(date_format)

In [7]:
comp_cfg = LandsatFusionComputationConfig(
    common_bands=["blue", "green", "red"], modis_interp_sample_rate=10
)

wrs_row = 23
wrs_path = 195
year = 2003
cloud_cover_limit = 20

In [8]:
start_day, end_day = get_borders_for_tile_and_year(relevant_landsat_df, wrs_path=wrs_path, wrs_row=wrs_row, year=year, cloud_cover_limit=cloud_cover_limit)

In [9]:
img_coll = compute_year_for_tile(
    wrs_path=wrs_path,
    wrs_row=wrs_row,
    start_date=start_day,
    end_date=end_day,
    year=2003,
    fusion_comp_cfg=comp_cfg
)

In [10]:
img_coll.size().getInfo()

EEException: Collection.toList: Empty date ranges not supported for the current operation.